"""The list of channels you actually want.

This is the single most important input for a large provider. Without it,
verification means probing every candidate for all 55,000 listed streams,
which is not a long job -- it is an impossible one. With it, probarr probes
only candidates for the couple of hundred channels you care about.

Format is deliberately the plainest thing that works, so it can be written by
hand, generated by a script, or pasted from a channel-lineup web page:

    # comments and blank lines ignored
    101: BBC One
    102: BBC Two
    BBC Four            <- number optional
    401: Meridian Sports Main Event | meridian.main.uk    <- optional tvg-id after |

    [Meridian Sports]                                  <- optional group header
    407: Meridian Sports 1
    408: Meridian Sports Golf

Numbering is preserved so an exported playlist can carry real channel numbers
rather than the order things happened to be probed in.

A `[Group Name]` line on its own sets the group for every channel line that
follows, until the next header (or end of file). This exists so Curate's
Groups view doesn't have to be rebuilt by hand on every new run of the same
lineup: a channel's group is a durable per-channel decision already carried
forward for an *existing* lineup (see lineups.py), but that inheritance has
nothing to inherit FROM on a lineup's very first run -- a header in the
wantlist itself seeds it from the start. It only ever seeds; a group set
afterwards in Curate always wins over what the wantlist says on the next run.
An empty `[]` resets to no group, for channels between two named sections
that don't belong in either.
"""
import difflib
import json
import os
import re
import urllib.request

TEMPLATE = """# probarr wantlist
#
# One channel per line. These are the channels you WANT -- probarr only probes
# candidate streams for these, which is the difference between a run that takes
# twenty minutes and one that never finishes.
#
# Format (everything except the name is optional):
#
#   <number>: <name> | <tvg-id>
#
#   101: BBC One                                name with a channel number
#   BBC Four                                    name only
#   401: Meridian Sports Main Event | meridian.main.uk    with an explicit EPG id
#
# The number is carried through to exported playlists, so your lineup keeps
# real channel numbers rather than the order things happened to be probed in.
# The tvg-id is only needed when a channel's guide listing cannot be found by
# name.
#
# Lines starting with # are ignored, as are blank lines.
#
# A [Group Name] line on its own sets the group for the channels that follow
# it, until the next one -- so Curate's Groups view starts already organised
# instead of being rebuilt by hand after every new lineup's first run.
#
# Names are matched loosely: case, punctuation and quality tags such as
# HD/FHD/UHD/4K are ignored, so "BBC One" will match a stream listed as
# "UKFHD | BBC One HD".
#
# Replace the examples below with your own channels.

[Entertainment]
101: BBC One
102: BBC Two
103: BBC Three
104: BBC Four
105: BBC Parliament
120: CBBC
121: CBeebies
130: S4C

[News & Business]
140: Bloomberg TV
"""


# Starter lineups: ready-to-import wantlists for real, well-known channel
# groupings, so a brand new lineup doesn't start from a blank textarea.
#
# Deliberately UK free-to-air ONLY for now -- numbers and names of channels
# that are already broadcast unencrypted, openly and for free, compiled from
# each broadcaster's own public channel listing. No streams, no logos, no
# provider details, nothing that came from any specific IPTV source. The
# equivalent for a subscription/branded lineup (Sky, DIRECTV and similar,
# which other open-source Dispatcharr tools do ship) is deliberately left
# out here for now -- a judgement call, not a technical limitation, kept
# separate so it can be revisited on its own later.
_STARTER_DISCLAIMER = """\
# This is a NUMBERING TEMPLATE, not a stream source -- it names channels and
# suggests channel numbers, nothing else. It carries no stream URLs, no
# logos, no EPG data and no provider details of any kind; probarr still
# matches every line here against whatever source you point it at
# separately.
#
# You are responsible for only ever pointing this at content you have the
# legal right to receive -- for UK free-to-air TV that generally means
# being in the UK and covered by a valid TV Licence where one is required.
# Nothing here is legal advice; if you are unsure, check before using it.
"""

STARTER_LINEUPS = {
    "uk-freeview": {
        "label": "UK Freeview (free-to-air)",
        # Deliberately just the 12 channels this project's own README/demo
        # runs already verify end-to-end (real BBC pips-CDN / S4C-CDN
        # stream URLs, probed clean, curated, exported into a live
        # Dispatcharr instance) -- not an attempt at a complete Freeview
        # lineup. Extending this to more channels means verifying each one
        # the same way first, not just listing names that sound plausible.
        "text": _STARTER_DISCLAIMER + """#
# The 12 channels this project's own demo runs are built against and have
# verified end-to-end. Numbers are grouped by genre band (entertainment
# 100s, kids 600s, shopping 150) so a second wantlist using the same
# convention can be imported alongside this one without collisions.

[Entertainment]
101: BBC One
102: BBC Two
103: BBC Three
104: BBC Four
105: BBC Parliament
106: BBC Scotland
107: BBC Alba
120: CBBC
121: CBeebies
130: S4C

[News & Business]
140: Bloomberg TV

[Shopping]
150: QVC UK
""",
    },
}


def list_starters():
    return [{"name": k, "label": v["label"]} for k, v in STARTER_LINEUPS.items()]


def get_starter(name):
    entry = STARTER_LINEUPS.get(name)
    return entry["text"] if entry else None


def safe_name(name):
    """Filesystem-safe wantlist name. None if nothing usable remains.

    Names arrive from the browser and become filenames, so this is a security
    boundary, not tidiness: anything outside the allowed set is replaced rather
    than stripped, so "../../etc/passwd" cannot survive as a path.

    Lowercased deliberately: filesystems here are case-sensitive, but the
    save UI treats a wantlist name as one identity regardless of how it was
    typed. Without this, saving "top10-us-paytv" and later re-saving under
    a differently-cased "Top-10-US-Pay-TV" (the display re-render, a typo,
    autocapitalize on mobile) silently created a second file instead of
    updating the first -- confirmed live, the two coexisted on the
    wantlists page, both claiming to be the same list.
    """
    cleaned = re.sub(r"[^A-Za-z0-9._-]", "-", (name or "").strip())[:64]
    cleaned = cleaned.strip("-.").lower()
    return cleaned or None


def store_dir(root):
    d = os.path.join(root, "wantlists")
    os.makedirs(d, exist_ok=True)
    return d


def list_saved(root):
    d = store_dir(root)
    out = []
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".txt"):
            continue
        path = os.path.join(d, fn)
        try:
            st = os.stat(path)
            with open(path, encoding="utf-8", errors="replace") as f:
                lines = sum(1 for line in f
                            if line.strip() and not line.strip().startswith("#"))
        except OSError:
            continue
        out.append({"name": fn[:-4], "channels": lines,
                    "bytes": st.st_size, "modified": st.st_mtime})
    return out


def read_saved(root, name):
    n = safe_name(name)
    if not n:
        return None
    path = os.path.join(store_dir(root), n + ".txt")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def write_saved(root, name, text):
    n = safe_name(name)
    if not n:
        raise ValueError("invalid wantlist name")
    path = os.path.join(store_dir(root), n + ".txt")
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)
    return n


def delete_saved(root, name):
    n = safe_name(name)
    if not n:
        return False
    path = os.path.join(store_dir(root), n + ".txt")
    if os.path.exists(path):
        os.remove(path)
        return True
    return False


def resolve_path(root, spec):
    """Accept either a filesystem path or the name of a saved wantlist.

    Lets --wantlist take 'my-lineup' as well as '/config/wantlists/my-lineup.txt',
    so a list created in the UI can be used from the CLI without the operator
    having to know where it was filed.
    """
    if os.path.exists(spec):
        return spec
    name = safe_name(spec)
    if name:
        candidate = os.path.join(store_dir(root), name + ".txt")
        if os.path.exists(candidate):
            return candidate
    return spec

_LINE_RE = re.compile(r"""
    ^\s*
    (?:(?P<number>\d{1,5})\s*[:.)\-]\s*)?   # optional leading channel number
    (?P<name>[^|]+?)                        # channel name
    (?:\s*\|\s*(?P<tvg>\S+))?               # optional |tvg-id
    \s*$
""", re.X)


class WantedChannel:
    __slots__ = ("number", "name", "tvg_id", "key", "group")

    def __init__(self, number, name, tvg_id, key, group=None):
        self.number, self.name, self.tvg_id, self.key = number, name, tvg_id, key
        self.group = group

    def as_dict(self):
        return {"number": self.number, "name": self.name,
                "tvg_id": self.tvg_id, "key": self.key, "group": self.group}


_GROUP_HEADER_RE = re.compile(r"^\[(.*)\]$")


def parse_detailed(text, normalizer):
    """Parse wantlist text. Returns (channels, warnings).

    Warnings are surfaced in the UI rather than dropped. A hand-written list
    picks up duplicates and typos, and a line silently ignored is a channel the
    operator believes is being checked and is not.
    """
    out, seen, warnings = [], {}, []
    current_group = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        gm = _GROUP_HEADER_RE.match(line)
        if gm:
            current_group = gm.group(1).strip() or None
            continue
        m = _LINE_RE.match(line)
        if not m:
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": "could not be parsed"})
            continue
        name = m.group("name").strip()
        if not name:
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": "no channel name"})
            continue
        key = normalizer.key(name)
        if not key:
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": "name normalises to nothing"})
            continue
        if key in seen:
            # A duplicate name under two different numbers is an easy slip in a
            # hand-written list, and silently keeping one of them is confusing
            # later. First occurrence wins, and the operator is told.
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": f"duplicate of line {seen[key]}, ignored"})
            continue
        seen[key] = lineno
        out.append(WantedChannel(
            int(m.group("number")) if m.group("number") else None,
            name, m.group("tvg") or "", key, current_group))
    return out, warnings


def parse(text, normalizer):
    """Parse wantlist text into WantedChannel objects, in file order."""
    return parse_detailed(text, normalizer)[0]


def load(path, normalizer):
    with open(path, encoding="utf-8", errors="replace") as f:
        return parse(f.read(), normalizer)


def render(channels):
    """Serialise WantedChannel objects back to wantlist text.

    Companion to parse_detailed(): a round trip through parse -> modify ->
    render is how enrichment (below) applies its changes, rather than trying
    to patch the original text in place and risk mangling a hand-written
    file's comments/spacing.
    """
    lines, current_group, first = [], "__unset__", True
    for c in channels:
        if c.group != current_group:
            if not first:
                lines.append("")
            lines.append(f"[{c.group}]" if c.group else "[]")
            current_group = c.group
        first = False
        prefix = f"{c.number}: " if c.number is not None else ""
        suffix = f" | {c.tvg_id}" if c.tvg_id else ""
        lines.append(f"{prefix}{c.name}{suffix}")
    return "\n".join(lines) + "\n"


def group_together(channels):
    """Reorder so every channel sharing a group sits in one contiguous run.

    parse_detailed() preserves file order, which is right for hand-written
    lists -- but after enrichment fills in groups from a reference lineup,
    the SAME group can now be scattered across the file wherever those
    channels originally happened to fall (e.g. wantlist order, or however
    an EPG source listed them). That makes render()'s one-header-per-run
    logic emit the same [Group] repeatedly instead of once, and makes it
    impossible to select a whole category and delete it in one go. Sorting
    by group here, stably and keyed on each group's first appearance (not
    alphabetically -- that would reshuffle a deliberate ordering someone
    already had), turns it back into one block per group.

    The ungrouped bucket (group is None/"") is always pushed to the end
    regardless of where it first appeared. It's typically the leftovers a
    reference lineup had no entry for, and after a broad EPG import that
    bucket can dwarf every real group combined -- left in its natural file
    position it can bury every properly-grouped, fully-numbered category
    underneath a long wall of blanks, which reads as if enrichment had
    simply stopped working partway through rather than run to completion.
    """
    order, seen = [], set()
    for c in channels:
        if c.group and c.group not in seen:
            seen.add(c.group)
            order.append(c.group)
    rank = {g: i for i, g in enumerate(order)}
    rank[None] = rank[""] = len(order)
    return sorted(channels, key=lambda c: rank[c.group])


_REFERENCE_INDEX_URL = ("https://api.github.com/repos/"
                         "PiratesIRC/Dispatcharr-Lineuparr-Plugin/contents/Lineuparr")
_REFERENCE_RAW_BASE = ("https://raw.githubusercontent.com/"
                        "PiratesIRC/Dispatcharr-Lineuparr-Plugin/main/Lineuparr/")
_REFERENCE_CACHE_NAME = "reference_lineups_cache.json"

_COUNTRY_NAMES = {
    "UK": "United Kingdom", "US": "United States", "CA": "Canada",
    "AU": "Australia", "FR": "France", "ES": "Spain", "NL": "Netherlands",
    "DE": "Germany", "IT": "Italy", "IE": "Ireland", "NZ": "New Zealand",
}


def _reference_cache_path(root):
    return os.path.join(store_dir(root), _REFERENCE_CACHE_NAME)


def _reference_label(filename):
    stem = filename[:-len(".json")]
    for suffix in ("_lineup", "-lineup"):
        if stem.lower().endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    code, _, rest = stem.partition("_")
    country = _COUNTRY_NAMES.get(code.upper())
    if country and rest:
        return country, rest.replace("_", " ").replace("-", " ").strip()
    if country:
        return country, country
    return "Other", stem.replace("_", " ").replace("-", " ").strip()


def known_reference_lineups(root, force=False):
    """The list of lineups Lineuparr currently publishes on GitHub.

    Discovered live from the repo's own directory listing rather than kept
    as a hand-maintained list here, so a lineup Lineuparr adds tomorrow
    shows up without a probarr release -- and one it removes doesn't leave
    a dead entry in the dropdown. Cached to disk and only re-fetched when
    asked (force=True), both to be a polite, low-frequency GitHub API
    caller and so the operator sees a stable list rather than it silently
    reordering itself mid-session.
    """
    cache_path = _reference_cache_path(root)
    if not force and os.path.exists(cache_path):
        with open(cache_path, encoding="utf-8") as f:
            return json.load(f)
    req = urllib.request.Request(_REFERENCE_INDEX_URL,
                                  headers={"User-Agent": "probarr/0.1",
                                           "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        entries = json.loads(resp.read())
    items = []
    for e in entries:
        name = e.get("name", "")
        if not name.endswith(".json") or name in ("plugin.json",):
            continue
        region, label = _reference_label(name)
        items.append({"file": name, "url": _REFERENCE_RAW_BASE + name,
                      "region": region, "label": label})
    items.sort(key=lambda i: (i["region"], i["label"]))
    tmp = cache_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(items, f)
    os.replace(tmp, cache_path)
    return items


def _walk_reference_categories(data, normalizer):
    """Yield (key, name, number, category) for every valid entry in a
    Lineuparr-style {"categories": {group: [{name, number}]}} JSON payload,
    deduplicated by normalized key (first occurrence wins).

    Shared by reference_lineup_map() and channels_from_reference() -- both
    read exactly this shape and both need the same validation and dedup
    rule, so it lives in one place rather than two copies that could drift.
    Format is the one used by the Lineuparr Dispatcharr plugin's published
    lineups (e.g. UK_SkyTV_lineup.json) -- real broadcaster channel numbers
    and genre groupings, something no XMLTV EPG carries. We only read this
    shape; nothing about it is probarr-specific or bundled into this repo,
    the operator supplies whichever lineup URL is relevant to them.
    """
    categories = data.get("categories") if isinstance(data, dict) else None
    if not isinstance(categories, dict):
        raise ValueError("not a recognised lineup format (expected a "
                          "'categories' object)")
    seen = set()
    for category, entries in categories.items():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            name = entry.get("name")
            number = entry.get("number")
            if not name:
                continue
            key = normalizer.key(str(name))
            if not key or key in seen:
                continue
            seen.add(key)
            yield key, str(name), number, category


def reference_lineup_map(data, normalizer):
    """Flatten a reference lineup into {normalized_key: (number, category)}."""
    return {key: (number, category)
           for key, _, number, category in _walk_reference_categories(data, normalizer)}


def channels_from_reference(data, normalizer):
    """Build a wantlist straight from a reference lineup's own channel list.

    Enrichment (reference_lineup_map + enrich_with_reference) assumes you
    already have a channel list from somewhere else -- an EPG, a hand-typed
    file -- and are only filling in numbers/groups it's missing. But a
    real broadcaster's EPG often names channels completely differently
    from its own lineup (Sky's on-screen guide text is character-limited
    and abbreviates: "SkySp F'ball HD" vs the lineup's "Sky Sports
    Football"), so matching EPG names against the lineup can miss most of
    it on naming alone.

    Skipping the EPG step entirely and using the lineup's own names as the
    channel list sidesteps that mismatch -- every name/number/group is
    already exactly what the lineup says, and probarr's own stream
    matching (which already tolerates real-world provider naming
    variance via Normalizer, unlike a rigid EPG-name-to-lineup-name
    lookup) is what finds the actual streams later, the same as any
    other hand-built wantlist.
    """
    return [WantedChannel(int(number) if isinstance(number, (int, float)) else None,
                          name, "", key, category or None)
           for key, name, number, category in _walk_reference_categories(data, normalizer)]


def enrich_with_reference(channels, reference_map):
    """Fill in missing channel numbers/groups from a reference lineup map.

    Only fills gaps -- an existing number or an existing group (whether from
    the wantlist file or inherited from a prior curated run) is never
    overwritten, since those reflect a decision already made for this
    lineup specifically. Returns (channels, matched_count).
    """
    matched = 0
    for c in channels:
        hit = reference_map.get(c.key)
        if not hit:
            continue
        number, category = hit
        changed = False
        if c.number is None and number is not None:
            c.number = int(number)
            changed = True
        if not c.group and category:
            c.group = category
            changed = True
        if changed:
            matched += 1
    return channels, matched


MIN_FUZZY_LEN = 5

# How much extra trailing text the REVERSE case (wantlist more specific than
# the listing) will tolerate before refusing to guess. A short qualifier like
# "UK" is almost certainly noise the user added; a whole extra word is not.
# Real, demonstrated case: "Comedy Central Xtra" (key "COMEDYCENTRALXTRA")
# reverse-matched the plain "Comedy Central" pool ("COMEDYCENTRAL" is a
# prefix of it) even though this provider's catalog has no distinct Xtra
# feed at all -- "Xtra" IS the whole point of that channel name, not a
# qualifier to discard. That silently gave two different Dispatcharr
# channels the exact same underlying stream under two different EPG
# identities, with no warning visible anywhere a curator would see it.
MAX_FUZZY_SUFFIX = 3


def _fuzzy(key, pools):
    """Closest pool key when the exact one is absent.

    Real playlists qualify names in ways a hand-written wantlist will not:
    "BBC One" is listed as "BBC One London", "Meridian Sports Main Event" as
    "Meridian Sports Main Event UK". So a wanted key that is a prefix of exactly
    one family of pool keys resolves to the shortest of them -- shortest
    because it is the least qualified, and therefore the most likely to be the
    plain channel rather than a regional variant.

    Guarded by a minimum length: a three-letter wanted name is a prefix of far
    too much to guess safely.
    """
    if len(key) < MIN_FUZZY_LEN:
        return None

    # Brand prefixes the provider and the wantlist disagree about.
    #
    # UKTV rebranded its channels with a "U&" prefix (U&Alibi, U&Yesterday,
    # U&Dave) but providers apply it inconsistently -- confirmed in one real
    # catalogue where "U&Dave" and "U&GOLD" are listed WITH it while Alibi,
    # Yesterday, Drama, Eden and W are listed without. A wantlist naming
    # them the official way therefore matched some and silently missed the
    # rest. Tried in both directions since either side may carry it.
    alts = []
    if key.startswith("UAND"):
        alts.append(key[4:])
    else:
        alts.append("UAND" + key)
    for alt in alts:
        if len(alt) >= MIN_FUZZY_LEN and alt in pools:
            return alt

    hits = [k for k in pools if k.startswith(key)]
    if not hits:
        # The reverse case: wantlist more specific than the listing. Capped
        # by MAX_FUZZY_SUFFIX -- see its docstring for why an unrestricted
        # version of this is a real bug, not just theoretical over-caution.
        hits = [k for k in pools if key.startswith(k) and len(k) >= MIN_FUZZY_LEN
               and len(key) - len(k) <= MAX_FUZZY_SUFFIX]
    if not hits:
        # The provider prefixes a platform brand the wantlist omits --
        # "Disney+ Cinema" listed as "Meridian Disney+ Cinema". Only accepted
        # when exactly one pool key ends with the wanted name, so a generic
        # short name cannot sweep up a family of unrelated channels.
        hits = [k for k in pools if k.endswith(key) and k != key]
        if len(hits) != 1:
            return None
    if not hits:
        return None
    return min(hits, key=len)


# Sensitivity presets for the token-sort stage -- the LAST resort, tried only
# after exact matching and every prefix/suffix stage in _fuzzy() has already
# failed. Idea from Lineuparr (another open-source Dispatcharr tool): a
# staged pipeline with an adjustable ceiling on how far the last, loosest
# stage is allowed to guess, rather than one fixed fuzzy behaviour for
# everyone. "strict" is every wantlist's behaviour before this existed --
# nothing changes unless a sensitivity is explicitly requested.
TOKEN_SORT_THRESHOLDS = {"strict": None, "normal": 0.86, "relaxed": 0.72}


def _token_set(name):
    """Lowercase word tokens, sorted -- order-independent comparison, so
    "Sports 1 Meridian" and "Meridian Sports 1" read as the same thing.
    Operates on the RAW name, not the folded key: folding strips spaces
    entirely, which throws away exactly the word-boundary information this
    stage needs.
    """
    return " ".join(sorted(re.findall(r"[a-z0-9]+", name.lower())))


def _token_sort_match(name, pools_by_name, threshold):
    """Best token-sort match for `name` among `pools_by_name` (pool key ->
    a representative raw stream name), or None if nothing clears
    `threshold` or the top two candidates are too close to call.

    Refuses ambiguity rather than guessing between close scores, the same
    rule every other stage here already follows -- a wrong guess here is a
    stream on the wrong channel with no visible sign anything was uncertain.
    """
    target = _token_set(name)
    scored = sorted(
        ((difflib.SequenceMatcher(None, target, _token_set(pname)).ratio(), key)
         for key, pname in pools_by_name.items()),
        reverse=True)
    if not scored or scored[0][0] < threshold:
        return None
    if len(scored) > 1 and (scored[0][0] - scored[1][0]) < 0.03:
        return None
    return scored[0][1]


def apply(wanted, pools, fuzzy=True, sensitivity="strict"):
    """Restrict candidate pools to wanted channels.

    Returns (filtered_pools, missing, fuzzy_matches). `missing` is the wanted
    channels with no candidate stream at all -- reported prominently, because a
    silently absent channel is indistinguishable from one that simply failed,
    and the usual cause is a name that needs an alias rather than a provider
    gap. `fuzzy_matches` is reported too: an inexact match is a guess, and a
    guess the operator cannot see is a guess they cannot correct.

    `sensitivity` controls only the LAST stage, token-sort fuzzy matching --
    "strict" (default) never tries it, matching every wantlist's behaviour
    before this existed. "normal"/"relaxed" try it only after every earlier,
    more precise stage in _fuzzy() has already failed.
    """
    threshold = TOKEN_SORT_THRESHOLDS.get(sensitivity)
    pools_by_name = None  # built lazily, only if token-sort is ever reached
    filtered, missing, fuzzy_matches = {}, [], []
    for w in wanted:
        streams = pools.get(w.key)
        if streams:
            filtered[w.key] = streams
            continue
        alt = _fuzzy(w.key, pools) if fuzzy else None
        if not alt and threshold is not None:
            if pools_by_name is None:
                pools_by_name = {k: v[0].name for k, v in pools.items() if v}
            alt = _token_sort_match(w.name, pools_by_name, threshold)
        if alt:
            filtered[w.key] = pools[alt]
            fuzzy_matches.append((w, alt))
        else:
            missing.append(w)
    return filtered, missing, fuzzy_matches
